using UnityEngine;
using UnityEngine.UI;
using TMPro;
using PdfGenerationModule.Core;
using PdfGenerationModule.Config;
using PdfGenerationModule.Storage;
using System.Collections.Generic;

namespace PdfGenerationModule.Demo
{
    // ─────────────────────────────────────────────────────────────────────────
    // MOCK DATA PROVIDER
    // Implements IPdfDataProvider with hardcoded checklist sample data.
    //
    // THIS IS THE DECOUPLING POINT.
    // Replace MockChecklistDataProvider with:
    //     ChecklistDataAdapter : IPdfDataProvider
    // The PDF module never changes — only this provider swaps out.
    // ─────────────────────────────────────────────────────────────────────────
    public class MockChecklistDataProvider : IPdfDataProvider
    {
        public string ProviderName => "MockChecklistDataProvider";

        public PdfDocumentData GetDocumentData()
        {
            var data = new PdfDocumentData
            {
                Title = "Safety Inspection Checklist",
                SubTitle = "Site: Block A  |  Inspector: Demo User  |  Date: "
                             + System.DateTime.Now.ToString("dd MMM yyyy"),
                FooterText = "Generated by PdfGenerationModule — Confidential"
            };

            // ── Section 1: Electrical ─────────────────────────────────────
            var electrical = new PdfSection { SectionTitle = "Electrical Checks" };
            electrical.Rows = new List<PdfRow>
            {
                new PdfRow { Label = "Main circuit breaker",  IsChecked = true,  HasCheckbox = true },
                new PdfRow { Label = "Emergency lighting",    IsChecked = true,  HasCheckbox = true },
                new PdfRow { Label = "Earthing connection",   IsChecked = false, HasCheckbox = true },
                new PdfRow { Label = "Panel labelling",       IsChecked = true,  HasCheckbox = true },
            };

            // ── Section 2: Mechanical ─────────────────────────────────────
            var mechanical = new PdfSection { SectionTitle = "Mechanical Checks" };
            mechanical.Rows = new List<PdfRow>
            {
                new PdfRow { Label = "Valve pressure",    Value = "4.2 bar", HasCheckbox = false },
                new PdfRow { Label = "Pipe insulation",   Value = "Good",    HasCheckbox = false },
                new PdfRow { Label = "Pump RPM",          Value = "1450",    HasCheckbox = false },
                new PdfRow { Label = "Gasket condition",  Value = "Replace", HasCheckbox = false },
            };

            // ── Section 3: Safety Equipment ───────────────────────────────
            var safety = new PdfSection { SectionTitle = "Safety Equipment" };
            safety.Rows = new List<PdfRow>
            {
                new PdfRow { Label = "Fire extinguisher", IsChecked = true,  HasCheckbox = true },
                new PdfRow { Label = "First aid kit",     IsChecked = true,  HasCheckbox = true },
                new PdfRow { Label = "Safety harness",    IsChecked = false, HasCheckbox = true },
            };

            data.Sections = new List<PdfSection> { electrical, mechanical, safety };
            return data;
        }

        // ── JSON Preview (shown in demo UI) ──────────────────────────────
        public string GetJsonPreview()
        {
            return JsonUtility.ToJson(GetDocumentData(), prettyPrint: true);
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // DEMO SCENE CONTROLLER
    // ─────────────────────────────────────────────────────────────────────────
    public class PdfGeneratorDemo : MonoBehaviour
    {
        [Header("── Config ──────────────────────────────")]
        [Tooltip("Drag the PdfGeneratorConfig ScriptableObject asset here")]
        [SerializeField] private PdfGeneratorConfig _config;

        [Header("── Buttons ─────────────────────────────")]
        [SerializeField] private Button _generateButton;
        [SerializeField] private Button _clearButton;
        [SerializeField] private Button _showDataButton;

        [Header("── Status Panel ────────────────────────")]
        [SerializeField] private TextMeshProUGUI _statusText;
        [SerializeField] private TextMeshProUGUI _filePathText;

        [Header("── Data Preview Panel ──────────────────")]
        [Tooltip("The panel that shows the JSON data preview")]
        [SerializeField] private GameObject _dataPreviewPanel;
        [SerializeField] private TextMeshProUGUI _dataPreviewText;
        [SerializeField] private Button _closePreviewButton;

        // Internal services
        private IPdfGeneratorService _generatorService;
        private MockChecklistDataProvider _dataProvider;
        private string _lastGeneratedPath;

        // ── Unity Lifecycle ───────────────────────────────────────────────

        private void Awake()
        {
            ValidateReferences();
            InitialiseServices();
            BindButtons();
        }

        private void Start()
        {
            SetStatus("Ready — press 'Preview Data' to see what will be in the PDF,\n" +
                      "then press 'Generate PDF' to create it.", Color.white);
            _filePathText.text = string.Empty;
            _clearButton.interactable = false;
            _dataPreviewPanel.SetActive(false);
        }

        // ── Button Handlers ───────────────────────────────────────────────

        private void OnShowDataClicked()
        {
            string json = _dataProvider.GetJsonPreview();
            _dataPreviewText.text =
                "── JSON sent to Android native plugin ──\n\n" + json +
                "\n\n── This exact structure generates the PDF ──";
            _dataPreviewPanel.SetActive(true);
        }

        private void OnClosePreviewClicked()
        {
            _dataPreviewPanel.SetActive(false);
        }

        private void OnGenerateClicked()
        {
            SetStatus("Generating PDF...", Color.yellow);
            _generateButton.interactable = false;

            string path = _generatorService.Generate(_dataProvider);

            if (!string.IsNullOrEmpty(path))
            {
                _lastGeneratedPath = path;
                _clearButton.interactable = true;
                _filePathText.text = "Saved to:\n" + path;
                SetStatus("PDF generated successfully!", Color.green);
            }
            else
            {
                _filePathText.text = string.Empty;
                SetStatus(
                    _generatorService.IsPlatformSupported
                        ? "Generation failed. Check console for errors."
                        : "Running in Editor — build to Android to generate a real PDF.\n" +
                          "Press 'Preview Data' to inspect what the PDF will contain.",
                    Color.yellow);
            }

            _generateButton.interactable = true;
        }

        private void OnClearClicked()
        {
            if (string.IsNullOrEmpty(_lastGeneratedPath)) return;

            new PdfStorageService(_config).DeleteFile(_lastGeneratedPath);
            _lastGeneratedPath = null;
            _filePathText.text = string.Empty;
            _clearButton.interactable = false;
            SetStatus("File deleted.", Color.gray);
        }

        // ── Setup Helpers ─────────────────────────────────────────────────

        private void InitialiseServices()
        {
            _dataProvider = new MockChecklistDataProvider();
            _generatorService = new PdfGeneratorService(
                                    _config,
                                    new PdfStorageService(_config));
        }

        private void BindButtons()
        {
            _generateButton.onClick.AddListener(OnGenerateClicked);
            _clearButton.onClick.AddListener(OnClearClicked);
            _showDataButton.onClick.AddListener(OnShowDataClicked);
            _closePreviewButton.onClick.AddListener(OnClosePreviewClicked);
        }

        private void ValidateReferences()
        {
            if (_config == null) Debug.LogError("[Demo] Config not assigned!");
            if (_generateButton == null) Debug.LogError("[Demo] GenerateButton not assigned!");
            if (_clearButton == null) Debug.LogError("[Demo] ClearButton not assigned!");
            if (_showDataButton == null) Debug.LogError("[Demo] ShowDataButton not assigned!");
            if (_statusText == null) Debug.LogError("[Demo] StatusText not assigned!");
            if (_filePathText == null) Debug.LogError("[Demo] FilePathText not assigned!");
            if (_dataPreviewPanel == null) Debug.LogError("[Demo] DataPreviewPanel not assigned!");
            if (_dataPreviewText == null) Debug.LogError("[Demo] DataPreviewText not assigned!");
            if (_closePreviewButton == null) Debug.LogError("[Demo] ClosePreviewButton not assigned!");
        }

        private void SetStatus(string message, Color color)
        {
            _statusText.text = message;
            _statusText.color = color;
            Debug.Log($"[PdfGeneratorDemo] {message}");
        }

        private void OnDestroy()
        {
            _generateButton.onClick.RemoveAllListeners();
            _clearButton.onClick.RemoveAllListeners();
            _showDataButton.onClick.RemoveAllListeners();
            _closePreviewButton.onClick.RemoveAllListeners();
        }
    }
}